name: Build libctags
run-name: ${{ github.actor }} testing github actions
on: [push, pull_request, workflow_dispatch]
env:
  BUILD_DIR: ${{ github.workspace }}\.temp

jobs:
  build:
    strategy:
      matrix:
        id: [x86, x64]
        include:
          - id: x86
            arch: Win32
          - id: x64
            arch: x64
 
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
#        with:
#          submodules: "recursive"

      - name: Matrix info
        run: |
          echo "id: ${{ matrix.id }}, arch: ${{ matrix.arch }}"

      - name: Make directories
        run: |
          md .temp

      - name: Generate
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          cmake -G "Visual Studio 17 2022" -A ${{ matrix.arch }} ..

      - name: Build
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          cmake --build . -v --config Release
