name: Build libctags
run-name: ${{ github.actor }} testing github actions
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: echo step1
      - run: echo step2
      - run: cmake --version
