name: Build libctags
run-name: ${{ github.actor }} testing github actions
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: cmake -G
      - run: echo preved
      - run: cmake --version
