name: Build libctags
run-name: "#${{ github.run_number }} ${{ github.event.head_commit.message }}. Run by ${{ github.actor }}"
on: [push, pull_request, workflow_dispatch]
env:
  VERSION_VAR: "3.2.1"

jobs:
#  GetVersion:
#    runs-on: ubuntu-latest
#    outputs:
#      version: ${{ steps.get.outputs.ver }}
#    steps:
#      - id: get
#        run: echo "ver=hello" >> "$GITHUB_OUTPUT"

  GetVersion:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get.outputs.ver }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - id: get
        run: |
          & ${{ github.workspace }}\.github\workflows\run.bat
          $outp = & ${{ github.workspace }}\.github\workflows\run.bat
          echo "++$outp"
          echo "ver=$outp" >> "$ENV:GITHUB_OUTPUT"

  job2:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    needs: GetVersion
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - env:
          OUTPUT1: ${{needs.GetVersion.outputs.version}}
        run: |
          echo "+++ %OUTPUT1%"
          fail.bat
          echo "--- ${{needs.GetVersion.outputs.version}}"

#  build:
#    strategy:
#      matrix:
#        id: [x86, x64]
#        include:
#          - id: x86
#            arch: Win32
#          - id: x64
#            arch: x64
#    runs-on: windows-latest
#    defaults:
#      run:
#        shell: cmd
#
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
##        with:
##          submodules: "recursive"
#
#      - name: Matrix info
#        run: |
#          echo "id: ${{ matrix.id }}, arch: ${{ matrix.arch }}"
#
#      - name: Make directories
#        run: |
#          set BUILD_DIR=${{ runner.temp }}
#          echo "Build dir: %BUILD_DIR%"
#          dir %BUILD_DIR%
#
#      - name: Run batch script
#        run: |
#          set BUILD_DIR=${{ runner.temp }}
#          .github\workflows\build.bat
#
#      - name: Generate
#        working-directory: ${{ runner.temp }}
#        run: |
#          cmake -G "Visual Studio 17 2022" -A ${{ matrix.arch }} ${{ github.workspace }}
#
#      - name: Build
#        working-directory: ${{ runner.temp }}
#        run: |
#          cmake --build . -v --config Release
